project:
  type: website

website:
  title: "Introduction to R"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    background: "#00A4CF"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

