project:
  type: website

website:
  title: "Introduction to R"
  navbar:
    logo: figure/logo.png
    logo-href: https://massbays-tech.github.io/MassWateR
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    background: "#00A4CF"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

