project:
  type: website

website:
  title: "Introduction to R"
  navbar:
    logo: figure/logo.png
    logo-href: https://massbays-tech.github.io/MassWateR
    left:
      - href: index.qmd
        text: Home
      - href: setup.qmd
        text: Setup
      - about.qmd
      - href: resources.qmd
        text: Resources
    background: "#00A4CF"
  page-footer: 
    left: "Content created by Marcus Beck" 
    right: 
      - icon: github
        href: https://github.com/massbays-tech/intro-to-r

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

